name: Cypress Tests
on: [push]
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2
 
     - name: Run Cypress Test
       uses: cypress-io/github-action@v4
       with:
         command: yarn cypress run ./cypress/TheMagento/**.* --browser chrome --headless --env allure=true --reporter mocha-allure-reporter
         browser: chrome
